package codegen

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/xavierli/nethelper/internal/store"
)

// tableSchemaYAML is the struct used to unmarshal the schema_yaml field of a rule.
type tableSchemaYAML struct {
	HeaderPattern string      `yaml:"header_pattern"`
	SkipLines     int         `yaml:"skip_lines"`
	Columns       []columnDef `yaml:"columns"`
	Derived       []derivedDef `yaml:"derived"`
}

type columnDef struct {
	Name        string `yaml:"name"`
	Index       int    `yaml:"index"`
	Type        string `yaml:"type"`
	Optional    bool   `yaml:"optional"`
	Description string `yaml:"description"`
}

// derivedDef describes a field that is computed from other parsed fields.
type derivedDef struct {
	Name        string   `yaml:"name"`
	Type        string   `yaml:"type"`
	Description string   `yaml:"description"`
	From        []string `yaml:"from"`
	Example     string   `yaml:"example"`
}

// CmdNameToGoIdent converts a command string to a CamelCase Go identifier fragment.
// "display traffic-policy statistics" → "TrafficPolicyStatistics"
func CmdNameToGoIdent(cmd string) string {
	lower := strings.ToLower(strings.TrimSpace(cmd))
	for _, prefix := range []string{"display ", "show ", "dis ", "sh "} {
		lower = strings.TrimPrefix(lower, prefix)
	}
	parts := strings.FieldsFunc(lower, func(r rune) bool { return r == ' ' || r == '-' || r == '_' })
	var sb strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			sb.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return sb.String()
}

// GoFuncName returns the generated parser function name.
func GoFuncName(vendor, cmd string) string {
	v := strings.ToUpper(vendor[:1]) + vendor[1:]
	return "Parse" + v + CmdNameToGoIdent(cmd)
}

// TargetFilePath returns the repo-relative path in snake_case.
// "huawei", "display traffic-policy statistics" → "internal/parser/huawei/traffic_policy_statistics.go"
func TargetFilePath(vendor, cmd string) string {
	lower := strings.ToLower(strings.TrimSpace(cmd))
	for _, prefix := range []string{"display ", "show ", "dis ", "sh "} {
		lower = strings.TrimPrefix(lower, prefix)
	}
	snakeRe := regexp.MustCompile(`[\s\-]+`)
	filename := snakeRe.ReplaceAllString(lower, "_")
	return fmt.Sprintf("internal/parser/%s/%s.go", vendor, filename)
}

// computeCmdTypeStr derives the unique CommandType string for a rule.
// "huawei", "display traffic-policy statistics interface" → "generated:huawei:traffic_policy_statistics_interface"
func computeCmdTypeStr(vendor, commandPattern string) string {
	lower := strings.ToLower(strings.TrimSpace(commandPattern))
	for _, pfx := range []string{"display ", "show ", "dis ", "sh "} {
		lower = strings.TrimPrefix(lower, pfx)
	}
	snakeRe := regexp.MustCompile(`[\s\-]+`)
	stem := snakeRe.ReplaceAllString(lower, "_")
	return fmt.Sprintf("generated:%s:%s", vendor, stem)
}

// GeneratorOptions configures a code generation run.
type GeneratorOptions struct {
	RepoRoot   string
	ApprovedBy string
	DryRun     bool
}

// GenerateParserFile generates the Go source for a parser file.
func GenerateParserFile(rule store.PendingRule) (string, error) {
	approvedBy := rule.ApprovedBy
	funcName := GoFuncName(rule.Vendor, rule.CommandPattern)

	var body, extraImport string
	if rule.OutputType == "table" {
		cmdTypeStr := computeCmdTypeStr(rule.Vendor, rule.CommandPattern)
		tb, err := generateTableBody(rule.SchemaYAML, funcName, cmdTypeStr)
		if err != nil {
			return "", err
		}
		body = tb
		extraImport = `"github.com/xavierli/nethelper/internal/parser/engine"`
	} else {
		body = fmt.Sprintf("func %s(raw string) (model.ParseResult, error) {\n\t%s\n}", funcName, rule.GoCodeDraft)
	}

	tplSrc := `// Code generated by nethelper rule-studio. DO NOT EDIT.
// Command:   {{.Command}}
// Vendor:    {{.Vendor}}
// Rule ID:   {{.RuleID}}
// Approved:  {{.Date}} by {{.ApprovedBy}}
// Regenerate: nethelper rule regen {{.RuleID}}
package {{.Vendor}}

import (
	"github.com/xavierli/nethelper/internal/model"{{if .ExtraImport}}
	{{.ExtraImport}}{{end}}
)

{{.Body}}
`
	tpl := template.Must(template.New("p").Parse(tplSrc))
	var buf bytes.Buffer
	err := tpl.Execute(&buf, map[string]any{
		"Command":     rule.CommandPattern,
		"Vendor":      rule.Vendor,
		"RuleID":      rule.ID,
		"Date":        time.Now().Format("2006-01-02"),
		"ApprovedBy":  approvedBy,
		"Body":        body,
		"ExtraImport": extraImport,
	})
	return buf.String(), err
}

func generateTableBody(schemaYAML, funcName, cmdTypeStr string) (string, error) {
	var schema tableSchemaYAML
	if err := yaml.Unmarshal([]byte(schemaYAML), &schema); err != nil {
		return "", err
	}

	// Validate derived field types and references.
	validFieldTypes := map[string]bool{"string": true, "int": true, "float": true, "bool": true}
	colNames := map[string]bool{}
	for _, c := range schema.Columns {
		colNames[c.Name] = true
	}
	for _, c := range schema.Columns {
		if c.Type != "" && !validFieldTypes[c.Type] {
			return "", fmt.Errorf("column %q has invalid type %q (must be string|int|float|bool)", c.Name, c.Type)
		}
	}
	for _, d := range schema.Derived {
		if !validFieldTypes[d.Type] {
			return "", fmt.Errorf("derived field %q has invalid type %q (must be string|int|float|bool)", d.Name, d.Type)
		}
		for _, ref := range d.From {
			if !colNames[ref] {
				return "", fmt.Errorf("derived field %q references unknown column %q", d.Name, ref)
			}
		}
	}

	var cols strings.Builder
	for _, c := range schema.Columns {
		cols.WriteString(fmt.Sprintf("\t\t{Name: %q, Index: %d, Type: %q, Optional: %v},\n",
			c.Name, c.Index, c.Type, c.Optional))
	}

	// Build the derived fields TODO block (only emitted when derived fields exist).
	var derivedBlock string
	if len(schema.Derived) > 0 {
		var db strings.Builder
		db.WriteString("\t// Derived fields — implement each TODO below\n")
		db.WriteString("\tfor i := range tableResult.Rows {\n")
		db.WriteString("\t\trow := tableResult.Rows[i]\n")
		for _, d := range schema.Derived {
			db.WriteString(fmt.Sprintf("\t\t// derived: %s (%s) from [%s]\n",
				d.Name, d.Type, strings.Join(d.From, ", ")))
			db.WriteString(fmt.Sprintf("\t\t// TODO: row[%q] = ...\n", d.Name))
		}
		db.WriteString("\t\t_ = row\n")
		db.WriteString("\t}\n")
		derivedBlock = db.String()
	}

	return fmt.Sprintf(`func %s(raw string) (model.ParseResult, error) {
	schema := engine.TableSchema{
		HeaderPattern: %q,
		SkipLines:     %d,
		Columns: []engine.ColumnDef{
%s		},
	}
	tableResult, err := engine.ParseTable(schema, raw)
	if err != nil {
		return model.ParseResult{RawText: raw}, err
	}
%s	return model.ParseResult{
		Type: model.CommandType(%q),
		RawText: raw,
		Rows: tableResult.Rows,
	}, nil
}`, funcName, schema.HeaderPattern, schema.SkipLines, cols.String(), derivedBlock, cmdTypeStr), nil
}

// GenerateTestFile generates a _test.go file with one test per test case.
func GenerateTestFile(rule store.PendingRule, testCases []store.RuleTestCase) (string, error) {
	funcName := GoFuncName(rule.Vendor, rule.CommandPattern)
	tplSrc := `// Code generated by nethelper rule-studio. DO NOT EDIT.
package {{.Vendor}}_test

import (
	"testing"

	"github.com/xavierli/nethelper/internal/parser/{{.Vendor}}"
)

{{range $i, $tc := .TestCases}}
func Test{{$.FuncName}}_Case{{$i}}(t *testing.T) {
	input := {{printf "%q" $tc.Input}}
	_, err := {{$.Vendor}}.{{$.FuncName}}(input)
	if err != nil {
		t.Errorf("case {{$i}}: unexpected error: %v", err)
	}
	// Expected result saved: {{$tc.Expected}}
	// TODO: parse expected JSON and assert returned fields (see deferred)
}
{{end}}
`
	tpl := template.Must(template.New("test").Parse(tplSrc))
	var buf bytes.Buffer
	err := tpl.Execute(&buf, map[string]any{
		"Vendor":    rule.Vendor,
		"FuncName":  funcName,
		"TestCases": testCases,
	})
	return buf.String(), err
}

// PatchGeneratedFile appends new cases to classifyGenerated(), parseGenerated(),
// knownGeneratedCmdTypes(), and generatedFieldSchema() in <vendor>_generated.go.
// Uses stable sentinel comments inside each switch/slice body.
// Exported so it can be tested from codegen_test package.
// vendor must be passed explicitly — do not derive from path (breaks in temp dirs).
// schemaYAML is used to populate the generatedFieldSchema case; pass "" for an empty (no-column) schema
func PatchGeneratedFile(path, commandPattern, funcName, vendor, schemaYAML string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	src := string(data)

	cmdTypeStr := computeCmdTypeStr(vendor, commandPattern)

	// Check for idempotency — skip patches if this cmdType is already patched
	if strings.Contains(src, cmdTypeStr) {
		return nil
	}

	// Patch 1: classifyGenerated
	const classifySentinel = "\t// GENERATED CASES — do not edit this comment"
	newClassifyCase := fmt.Sprintf("\tcase strings.HasPrefix(cmd, %q):\n\t\treturn model.CommandType(%q) // %s\n%s",
		commandPattern, cmdTypeStr, funcName, classifySentinel)
	patched := strings.Replace(src, classifySentinel, newClassifyCase, 1)
	if patched == src {
		return fmt.Errorf("patchGeneratedFile: classify sentinel not found in %s", path)
	}

	// Patch 2: parseGenerated
	intermediate := patched
	const parseSentinel = "\t// GENERATED PARSE CASES — do not edit this comment"
	newParseCase := fmt.Sprintf("\tcase model.CommandType(%q):\n\t\treturn %s(raw)\n%s",
		cmdTypeStr, funcName, parseSentinel)
	patched = strings.Replace(patched, parseSentinel, newParseCase, 1)
	if patched == intermediate {
		return fmt.Errorf("patchGeneratedFile: parse sentinel not found in %s", path)
	}

	// Patch 3: knownGeneratedCmdTypes — silent if sentinel absent (function may not exist yet)
	const cmdTypesSentinel = "\t\t// GENERATED CMDTYPES — do not edit this comment"
	cmdTypeLine := fmt.Sprintf("\t\tmodel.CommandType(%q),\n%s", cmdTypeStr, cmdTypesSentinel)
	patched = strings.Replace(patched, cmdTypesSentinel, cmdTypeLine, 1)

	// Patch 4: generatedFieldSchema — silent if sentinel absent (function may not exist yet)
	const fieldCasesSentinel = "\t// GENERATED FIELD CASES — do not edit this comment"
	fieldSchemaCase := buildFieldSchemaCase(cmdTypeStr, schemaYAML)
	fieldCaseLine := fieldSchemaCase + "\n" + fieldCasesSentinel
	patched = strings.Replace(patched, fieldCasesSentinel, fieldCaseLine, 1)

	// Add "strings" import if this is the first case
	if !strings.Contains(patched, `"strings"`) {
		patched = strings.Replace(patched,
			`import "github.com/xavierli/nethelper/internal/model"`,
			"import (\n\t\"strings\"\n\n\t\"github.com/xavierli/nethelper/internal/model\"\n)", 1)
	}

	return os.WriteFile(path, []byte(patched), 0644)
}

// buildFieldSchemaCase generates the Go case block for generatedFieldSchema().
func buildFieldSchemaCase(cmdTypeStr, schemaYAML string) string {
	var schema tableSchemaYAML
	if err := yaml.Unmarshal([]byte(schemaYAML), &schema); err != nil {
		return fmt.Sprintf("\tcase model.CommandType(%q):\n\t\treturn nil", cmdTypeStr)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "\tcase model.CommandType(%q):\n", cmdTypeStr)
	fmt.Fprintf(&b, "\t\treturn []model.FieldDef{\n")
	for _, c := range schema.Columns {
		fmt.Fprintf(&b, "\t\t\t{Name: %q, Type: model.FieldType%s, Description: %q},\n",
			c.Name, capitalizeFirst(c.Type), c.Description)
	}
	for _, d := range schema.Derived {
		fmt.Fprintf(&b, "\t\t\t{Name: %q, Type: model.FieldType%s, Description: %q, Derived: true, DerivedFrom: %#v},\n",
			d.Name, capitalizeFirst(d.Type), d.Description, d.From)
	}
	fmt.Fprintf(&b, "\t\t}")
	return b.String()
}

// capitalizeFirst uppercases the first rune of s.
func capitalizeFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// Generate performs the full code generation, git commit, and PR creation.
// Returns the PR URL on success.
func Generate(rule store.PendingRule, testCases []store.RuleTestCase, opts GeneratorOptions) (string, error) {
	if !opts.DryRun {
		if err := checkGH(); err != nil {
			return "", err
		}
	}

	parserSrc, err := GenerateParserFile(rule)
	if err != nil {
		return "", fmt.Errorf("generate parser: %w", err)
	}
	testSrc, err := GenerateTestFile(rule, testCases)
	if err != nil {
		return "", fmt.Errorf("generate test: %w", err)
	}

	relParser := TargetFilePath(rule.Vendor, rule.CommandPattern)
	relTest := strings.TrimSuffix(relParser, ".go") + "_test.go"
	relGenerated := fmt.Sprintf("internal/parser/%s/%s_generated.go", rule.Vendor, rule.Vendor)

	parserPath := filepath.Join(opts.RepoRoot, relParser)
	testPath := filepath.Join(opts.RepoRoot, relTest)
	generatedPath := filepath.Join(opts.RepoRoot, relGenerated)

	if opts.DryRun {
		fmt.Printf("=== %s ===\n%s\n\n=== %s ===\n%s\n", parserPath, parserSrc, testPath, testSrc)
		return "", nil
	}

	if err := os.MkdirAll(filepath.Dir(parserPath), 0755); err != nil {
		return "", err
	}
	if err := os.WriteFile(parserPath, []byte(parserSrc), 0644); err != nil {
		return "", err
	}
	if err := os.WriteFile(testPath, []byte(testSrc), 0644); err != nil {
		return "", err
	}

	funcName := GoFuncName(rule.Vendor, rule.CommandPattern)
	if err := PatchGeneratedFile(generatedPath, rule.CommandPattern, funcName, rule.Vendor, rule.SchemaYAML); err != nil {
		return "", fmt.Errorf("patch _generated.go: %w", err)
	}

	stem := strings.TrimSuffix(filepath.Base(relParser), ".go")
	branch := fmt.Sprintf("rule/%s-%s-%d", rule.Vendor, stem, rule.ID)

	run := func(args ...string) error {
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = opts.RepoRoot
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		return cmd.Run()
	}

	runOutput := func(args ...string) (string, error) {
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = opts.RepoRoot
		cmd.Stderr = os.Stderr
		out, err := cmd.Output()
		return strings.TrimSpace(string(out)), err
	}

	if err := run("git", "checkout", "-b", branch); err != nil {
		return "", fmt.Errorf("git checkout: %w", err)
	}
	if err := run("git", "add", relParser, relTest, relGenerated); err != nil {
		return "", fmt.Errorf("git add: %w", err)
	}
	msg := fmt.Sprintf("feat(parser): add %s parser for %q\n\nCo-Authored-By: nethelper rule-studio <noreply@nethelper>", rule.Vendor, rule.CommandPattern)
	if err := run("git", "commit", "-m", msg); err != nil {
		return "", fmt.Errorf("git commit: %w", err)
	}
	if err := run("git", "push", "-u", "origin", branch); err != nil {
		return "", fmt.Errorf("git push: %w", err)
	}

	approvedBy := opts.ApprovedBy
	body := fmt.Sprintf("Auto-generated by nethelper rule-studio.\n\n**Vendor:** %s\n**Command:** %s\n**Rule ID:** %d\n**Approved by:** %s\n**Test cases:** %d",
		rule.Vendor, rule.CommandPattern, rule.ID, approvedBy, len(testCases))
	prURL, err := runOutput("gh", "pr", "create",
		"--title", fmt.Sprintf("feat(parser): %s %s", rule.Vendor, rule.CommandPattern),
		"--body", body)
	if err != nil {
		return "", fmt.Errorf("gh pr create: %w", err)
	}
	return prURL, nil
}

func checkGH() error {
	if _, err := exec.LookPath("gh"); err != nil {
		return fmt.Errorf("gh CLI not found — install from https://cli.github.com and run 'gh auth login'")
	}
	if err := exec.Command("gh", "auth", "status").Run(); err != nil {
		return fmt.Errorf("gh CLI not authenticated — run 'gh auth login'")
	}
	return nil
}
