// Code generated by nethelper rule-studio. DO NOT EDIT.
// Command:   display acl {id}
// Vendor:    huawei
// Rule ID:   19
// Approved:  2026-03-28 by 
// Regenerate: nethelper rule regen 19
package huawei

import (
	"github.com/xavierli/nethelper/internal/model"
	"github.com/xavierli/nethelper/internal/parser/engine"
)

func ParseHuaweiAcl(raw string) (model.ParseResult, error) {
	dsl := `# ACL header extraction - broadcast to all rules
# The acl_name is on the line after the header, not in the first line
REPEAT_FOR ^(?P<acl_type>Basic|Advanced) IPv4 ACL (?P<acl_id>\d+),\s*(?P<rule_count>\d+) rules,
# Capture acl_name from the next line (the line right after the header)
REGEX ^(?P<acl_name>\S+)$
# Capture step and start ID info
REGEX ^ACL's step is (?P<acl_step>\d+), start ID is (?P<start_id>\d+)$
# Extract each rule line
FILTER ^rule\s+\d+
# Parse rule: rule <id> <action> [vpn-instance <vrf>] source <ip> <wildcard> [(<matched> times matched)]
REGEX ^rule\s+(?P<rule_id>\d+)\s+(?P<action>permit|deny)(?:\s+vpn-instance\s+(?P<vrf>\S+))?\s+source\s+(?P<source_ip>\S+)\s+(?P<wildcard>\S+)(?:\s*\((?P<matched>\d+)\s+times\s+matched\))?$`
	result, err := engine.ExecPipeline(dsl, raw)
	if err != nil {
		return model.ParseResult{RawText: raw}, err
	}
	return model.ParseResult{
		Type:    model.CommandType("generated:huawei:acl"),
		RawText: raw,
		Rows:    result.Rows,
	}, nil
}
