// Code generated by nethelper rule-studio. DO NOT EDIT.
// Command:   display acl all
// Vendor:    huawei
// Rule ID:   20
// Approved:  2026-03-28 by 
// Regenerate: nethelper rule regen 20
package huawei

import (
	"github.com/xavierli/nethelper/internal/model"
	"github.com/xavierli/nethelper/internal/parser/engine"
)

func ParseHuaweiAclAll(raw string) (model.ParseResult, error) {
	dsl := `# Split input into ACL blocks, each starting with "Basic IPv4 ACL" or "Advanced IPv4 ACL"
REPEAT_FOR ^(?P<acl_type>Basic|Advanced) IPv4 ACL (?P<acl_number>\d+), (?P<rule_count>\d+) rules,$
# Capture ACL name (line after header) - skip the header line first then capture
SKIP_LINES 1
REGEX ^(?P<acl_name>\S+)$
# Skip to rule lines (step line and any blank lines)
SKIP_UNTIL ^rule\s+\d+
# Within each ACL block, process rule lines
FILTER ^rule\s+\d+
# Extract rule details - handle optional vpn-instance and optional match count
# Note: rule 60 has no match count, so the matched group must be optional
REGEX ^rule\s+(?P<rule_id>\d+)\s+(?P<action>permit|deny)(?:\s+vpn-instance\s+(?P<vpn_instance>\S+))?\s+source\s+(?P<source_ip>\S+)\s+(?P<source_wildcard>\S+)(?:\s+\((?P<matched>\d+)\s+times?\s+matched\))?$`
	result, err := engine.ExecPipeline(dsl, raw)
	if err != nil {
		return model.ParseResult{RawText: raw}, err
	}
	return model.ParseResult{
		Type:    model.CommandType("generated:huawei:acl_all"),
		RawText: raw,
		Rows:    result.Rows,
	}, nil
}
