// Code generated by nethelper rule-studio. DO NOT EDIT.
package huawei_test

import (
	"testing"

	"github.com/xavierli/nethelper/internal/parser/huawei"
)


func TestParseHuaweiAclAll_Case0(t *testing.T) {
	input := "Basic IPv4 ACL 2000, 14 rules,\nSsh-Filter\nACL's step is 5, start ID is 0\nrule 0 permit source 172.16.0.192 0.0.0.63\nrule 5 permit source 172.17.73.0 0.0.0.31\nrule 10 permit source 172.18.62.0 0.0.0.31\nrule 15 permit source 10.12.212.224 0.0.0.31\nrule 20 permit source 10.12.220.0 0.0.0.255\nrule 25 permit vpn-instance mgt_vrf source 172.16.0.192 0.0.0.63 (118 times matched)\nrule 30 permit vpn-instance mgt_vrf source 172.17.73.0 0.0.0.31\nrule 35 permit vpn-instance mgt_vrf source 172.18.62.0 0.0.0.31\nrule 40 permit vpn-instance mgt_vrf source 10.12.212.224 0.0.0.31 (120 times matched)\nrule 45 permit vpn-instance mgt_vrf source 10.12.220.0 0.0.0.255 (20 times matched)\nrule 50 permit vpn-instance mgt_vrf source 11.224.206.0 0.0.0.255\nrule 55 permit vpn-instance mgt_vrf source 100.127.43.231 0 (11768 times matched)\nrule 60 permit vpn-instance mgt_vrf source 100.127.43.232 0\nrule 65 permit vpn-instance mgt_vrf source 100.127.43.233 0 (1128 times matched)\n\nBasic IPv4 ACL 2001, 14 rules,\nSNMP-Filter\nACL's step is 5, start ID is 0\nrule 0 permit source 172.16.0.192 0.0.0.63\nrule 5 permit source 172.17.73.0 0.0.0.31\nrule 10 permit source 172.18.62.0 0.0.0.31\nrule 15 permit source 10.12.212.224 0.0.0.31\nrule 20 permit source 10.12.220.0 0.0.0.255\nrule 25 permit vpn-instance mgt_vrf source 172.16.0.192 0.0.0.63 (24 times matched)\nrule 30 permit vpn-instance mgt_vrf source 172.17.73.0 0.0.0.31\nrule 35 permit vpn-instance mgt_vrf source 172.18.62.0 0.0.0.31\nrule 40 permit vpn-instance mgt_vrf source 10.12.212.224 0.0.0.31\nrule 45 permit vpn-instance mgt_vrf source 10.12.220.0 0.0.0.255\nrule 50 permit vpn-instance mgt_vrf source 11.224.206.0 0.0.0.255\nrule 55 permit vpn-instance mgt_vrf source 100.127.43.231 0 (907808 times matched)\nrule 60 permit vpn-instance mgt_vrf source 100.127.43.232 0\nrule 65 permit vpn-instance mgt_vrf source 100.127.43.233 0 (52398910 times matched)\n\n<GZ-YS-0306-A02-H12504AF-GWWC-003>"
	_, err := huawei.ParseHuaweiAclAll(input)
	if err != nil {
		t.Errorf("case 0: unexpected error: %v", err)
	}
	// Expected result saved: {
  "rows": [
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "10",
      "source_ip": "172.18.62.0",
      "source_wildcard": "0.0.0.31",
      "vpn_instance": ""
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "15",
      "source_ip": "10.12.212.224",
      "source_wildcard": "0.0.0.31",
      "vpn_instance": ""
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "20",
      "source_ip": "10.12.220.0",
      "source_wildcard": "0.0.0.255",
      "vpn_instance": ""
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "118",
      "rule_count": "14",
      "rule_id": "25",
      "source_ip": "172.16.0.192",
      "source_wildcard": "0.0.0.63",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "30",
      "source_ip": "172.17.73.0",
      "source_wildcard": "0.0.0.31",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "35",
      "source_ip": "172.18.62.0",
      "source_wildcard": "0.0.0.31",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "120",
      "rule_count": "14",
      "rule_id": "40",
      "source_ip": "10.12.212.224",
      "source_wildcard": "0.0.0.31",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "20",
      "rule_count": "14",
      "rule_id": "45",
      "source_ip": "10.12.220.0",
      "source_wildcard": "0.0.0.255",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "50",
      "source_ip": "11.224.206.0",
      "source_wildcard": "0.0.0.255",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "11768",
      "rule_count": "14",
      "rule_id": "55",
      "source_ip": "100.127.43.231",
      "source_wildcard": "0",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "60",
      "source_ip": "100.127.43.232",
      "source_wildcard": "0",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2000",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "1128",
      "rule_count": "14",
      "rule_id": "65",
      "source_ip": "100.127.43.233",
      "source_wildcard": "0",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "10",
      "source_ip": "172.18.62.0",
      "source_wildcard": "0.0.0.31",
      "vpn_instance": ""
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "15",
      "source_ip": "10.12.212.224",
      "source_wildcard": "0.0.0.31",
      "vpn_instance": ""
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "20",
      "source_ip": "10.12.220.0",
      "source_wildcard": "0.0.0.255",
      "vpn_instance": ""
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "24",
      "rule_count": "14",
      "rule_id": "25",
      "source_ip": "172.16.0.192",
      "source_wildcard": "0.0.0.63",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "30",
      "source_ip": "172.17.73.0",
      "source_wildcard": "0.0.0.31",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "35",
      "source_ip": "172.18.62.0",
      "source_wildcard": "0.0.0.31",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "40",
      "source_ip": "10.12.212.224",
      "source_wildcard": "0.0.0.31",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "45",
      "source_ip": "10.12.220.0",
      "source_wildcard": "0.0.0.255",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "50",
      "source_ip": "11.224.206.0",
      "source_wildcard": "0.0.0.255",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "907808",
      "rule_count": "14",
      "rule_id": "55",
      "source_ip": "100.127.43.231",
      "source_wildcard": "0",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "",
      "rule_count": "14",
      "rule_id": "60",
      "source_ip": "100.127.43.232",
      "source_wildcard": "0",
      "vpn_instance": "mgt_vrf"
    },
    {
      "acl_number": "2001",
      "acl_type": "Basic",
      "action": "permit",
      "matched": "52398910",
      "rule_count": "14",
      "rule_id": "65",
      "source_ip": "100.127.43.233",
      "source_wildcard": "0",
      "vpn_instance": "mgt_vrf"
    }
  ],
  "columns": [
    "acl_type",
    "acl_number",
    "rule_count",
    "acl_name",
    "rule_id",
    "action",
    "vpn_instance",
    "source_ip",
    "source_wildcard",
    "matched"
  ],
  "mode": "table"
}
	// TODO: parse expected JSON and assert returned fields (see deferred)
}

