// Code generated by nethelper rule-studio. DO NOT EDIT.
// Command:   display bgp network ipv4
// Vendor:    huawei
// Rule ID:   24
// Approved:  2026-03-28 by 
// Regenerate: nethelper rule regen 24
package huawei

import (
	"github.com/xavierli/nethelper/internal/model"
	"github.com/xavierli/nethelper/internal/parser/engine"
)

func ParseHuaweiBgpNetworkIpv4(raw string) (model.ParseResult, error) {
	dsl := `# Skip header lines until the table header
SKIP_UNTIL ^Network\s+Mask\s+Route-policy\s+Short-cut
# Skip the separator line (dashes)
SKIP_LINES 0
# Skip blank lines
SKIP_BLANK
# Stop at prompt or end of table
STOP_AT ^<
# Extract tabular data
SPLIT $network $mask $route_policy $short_cut
EMIT`
	result, err := engine.ExecPipeline(dsl, raw)
	if err != nil {
		return model.ParseResult{RawText: raw}, err
	}
	return model.ParseResult{
		Type:    model.CommandType("generated:huawei:bgp_network_ipv4"),
		RawText: raw,
		Rows:    result.Rows,
	}, nil
}
