// Code generated by nethelper rule-studio. DO NOT EDIT.
package huawei_test

import (
	"testing"

	"github.com/xavierli/nethelper/internal/parser/huawei"
)


func TestParseHuaweiBgpNetworkIpv4_Case0(t *testing.T) {
	input := "\nBGP local router ID: 11.240.168.151\nLocal AS number: 50519\n\nNetwork           Mask            Route-policy        Short-cut   \n11.49.129.0       255.255.255.192 SetComm-1/1         No        \n11.49.133.0       255.255.255.192 SetComm-1/2         No        \n11.49.153.0       255.255.255.128 SetComm-1/1         No        \n11.49.160.0       255.255.254.0   SetComm-1/1         No        \n11.55.100.149     255.255.255.255 SetComm-1/4         No        \n<SH-HQ-7209-A13-H9850C-XGWL-03>"
	_, err := huawei.ParseHuaweiBgpNetworkIpv4(input)
	if err != nil {
		t.Errorf("case 0: unexpected error: %v", err)
	}
	// Expected result saved: {
  "rows": [
    {
      "mask": "255.255.255.192",
      "network": "11.49.129.0",
      "route_policy": "SetComm-1/1",
      "short_cut": "No"
    },
    {
      "mask": "255.255.255.192",
      "network": "11.49.133.0",
      "route_policy": "SetComm-1/2",
      "short_cut": "No"
    },
    {
      "mask": "255.255.255.128",
      "network": "11.49.153.0",
      "route_policy": "SetComm-1/1",
      "short_cut": "No"
    },
    {
      "mask": "255.255.254.0",
      "network": "11.49.160.0",
      "route_policy": "SetComm-1/1",
      "short_cut": "No"
    },
    {
      "mask": "255.255.255.255",
      "network": "11.55.100.149",
      "route_policy": "SetComm-1/4",
      "short_cut": "No"
    }
  ],
  "columns": [
    "network",
    "mask",
    "route_policy",
    "short_cut"
  ],
  "mode": "table"
}
	// TODO: parse expected JSON and assert returned fields (see deferred)
}

