// Code generated by nethelper rule-studio. DO NOT EDIT.
// Command:   display ip inter brief
// Vendor:    huawei
// Rule ID:   4
// Approved:  2026-03-27 by 
// Regenerate: nethelper rule regen 4
package huawei

import (
	"github.com/xavierli/nethelper/internal/model"
	"github.com/xavierli/nethelper/internal/parser/engine"
)

func ParseHuaweiIpInterBrief(raw string) (model.ParseResult, error) {
	dsl := `# Huawei display ip interface brief parser
# Skip legend lines at the top
SKIP_UNTIL ^Interface\s+Physical\s+Protocol\s+IP\s+Address
# Skip the header line itself and any separator
SKIP_LINES 1
# Process data lines - whitespace separated columns
# Format: Interface Physical Protocol IP_Address Description...
SPLIT $interface $physical $protocol $ip_address $description
# Filter out empty lines and prompt lines
REJECT ^\s*$
REJECT ^<.*>$`
	result, err := engine.ExecPipeline(dsl, raw)
	if err != nil {
		return model.ParseResult{RawText: raw}, err
	}
	return model.ParseResult{
		Type:    model.CommandType("generated:huawei:ip_inter_brief"),
		RawText: raw,
		Rows:    result.Rows,
	}, nil
}
