// Code generated by nethelper rule-studio. DO NOT EDIT.
package huawei_test

import (
	"testing"

	"github.com/xavierli/nethelper/internal/parser/huawei"
)


func TestParseHuaweiLinkAggregationVerboseBridgeAggregation1_Case0(t *testing.T) {
	input := "Loadsharing Type: Shar -- Loadsharing, NonS -- Non-Loadsharing \nPort Status: S -- Selected, U -- Unselected, I -- Individual \nFlags:  A -- LACP_Activity, B -- LACP_Timeout, C -- Aggregation, \nD -- Synchronization, E -- Collecting, F -- Distributing,  \nG -- Defaulted, H -- Expired\n\nAggregate Interface: Bridge-Aggregation1\nAggregation Mode: Dynamic\nLoadsharing Type: Shar\nSystem ID: 0x8000, 3c8c-4004-d3d0\nLocal: \nPort             Status  Priority Oper-Key  Flag\n--------------------------------------------------------------------------------\nXGE2/0/35:1      S       32768    1         {ACDEF}\nXGE3/0/35:1      S       32768    1         {ACDEF}\nRemote: \nActor            Partner Priority Oper-Key  SystemID               Flag   \n--------------------------------------------------------------------------------\nXGE2/0/35:1      5       32768    4         0x8000, 741f-4a2e-0aa0 {ACDEF}\nXGE3/0/35:1      6       32768    4         0x8000, 741f-4a2e-0aa0 {ACDEF}\n<SH-YQ-0502-E16-H12516AF-LC-01>"
	_, err := huawei.ParseHuaweiLinkAggregationVerboseBridgeAggregation1(input)
	if err != nil {
		t.Errorf("case 0: unexpected error: %v", err)
	}
	// Expected result saved: {"rows":[{"local_port":"XGE2/0/35:1","local_status":"S"},{"local_port":"XGE3/0/35:1","local_status":"S"}]}
	// TODO: parse expected JSON and assert returned fields (see deferred)
}

