// Code generated by nethelper rule-studio. DO NOT EDIT.
// Command:   display link-aggregation verbose bridge-aggregation 1
// Vendor:    huawei
// Rule ID:   6
// Approved:  2026-03-26 by 
// Regenerate: nethelper rule regen 6
package huawei

import (
	"github.com/xavierli/nethelper/internal/model"
	"github.com/xavierli/nethelper/internal/parser/engine"
)

func ParseHuaweiLinkAggregationVerboseBridgeAggregation1(raw string) (model.ParseResult, error) {
	dsl := `# Section 1: Local ports
SKIP_UNTIL ^Port\s+Status\s+Priority
SKIP_LINES 1
SKIP_BLANK
STOP_AT ^Remote:
REJECT ^-+$
REPLACE \{|\} ""
SPLIT $local_port $local_status $local_priority $local_oper_key $local_flag

SECTION

# Section 2: Remote ports
SKIP_UNTIL ^Actor\s+Partner\s+Priority
SKIP_LINES 1
SKIP_BLANK
STOP_AT ^<
REJECT ^-+$
REPLACE \{|\} ""
SPLIT $remote_port $remote_partner $remote_priority $remote_oper_key $remote_sys1 $remote_sys2 $remote_flag
SET $remote_systemid $remote_sys1 " " $remote_sys2
`
	result, err := engine.ExecPipeline(dsl, raw)
	if err != nil {
		return model.ParseResult{RawText: raw}, err
	}
	return model.ParseResult{
		Type:    model.CommandType("generated:huawei:link_aggregation_verbose_bridge_aggregation_1"),
		RawText: raw,
		Rows:    result.Rows,
	}, nil
}
