// Code generated by nethelper rule-studio. DO NOT EDIT.
// Command:   display route-policy {name} no-more
// Vendor:    huawei
// Rule ID:   18
// Approved:  2026-03-27 by 
// Regenerate: nethelper rule regen 18
package huawei

import (
	"github.com/xavierli/nethelper/internal/model"
	"github.com/xavierli/nethelper/internal/parser/engine"
)

func ParseHuaweiRoutePolicyNoMore(raw string) (model.ParseResult, error) {
	dsl := `# Parse H3C display route-policy output
# Each route-policy has a name, then multiple permit/deny nodes within it.
# Use nested REPEAT_FOR: outer splits by route-policy name, inner splits by permit/deny.

STOP_AT ^<
REPEAT_FOR ^Route-policy:\s+(?P<route_policy_name>.+)$
REPEAT_FOR ^\s*(?P<action>permit|deny)\s*:\s*(?P<seq>\d+)\s*\(matched counts:\s*(?P<matched_counts>\d+)\)
REGEX ^\s*if-match\s+(?P<match_clause>.+)$
REGEX ^\s*apply\s+(?P<apply_clause>.+)$`
	result, err := engine.ExecPipeline(dsl, raw)
	if err != nil {
		return model.ParseResult{RawText: raw}, err
	}
	return model.ParseResult{
		Type:    model.CommandType("generated:huawei:route_policy_no_more"),
		RawText: raw,
		Rows:    result.Rows,
	}, nil
}
