// Code generated by nethelper rule-studio. DO NOT EDIT.
// This file is maintained by the Code Generator. Add rules via `nethelper rule studio`.
package juniper

import "github.com/xavierli/nethelper/internal/model"

// classifyGenerated is a fallback called by ClassifyCommand when the main switch
// returns CmdUnknown. Rule Studio inserts cases here automatically.
func classifyGenerated(cmd string) model.CommandType {
	switch {
	// GENERATED CASES — do not edit this comment
	}
	return model.CmdUnknown
}

// parseGenerated is a fallback called by ParseOutput for Rule Studio-generated commands.
// Rule Studio inserts dispatch cases here automatically (one per approved rule).
func parseGenerated(cmdType model.CommandType, raw string) (model.ParseResult, error) {
	switch cmdType {
	// GENERATED PARSE CASES — do not edit this comment
	}
	return model.ParseResult{Type: cmdType, RawText: raw}, nil
}
