// Code generated by nethelper rule-studio. DO NOT EDIT.
// Command:   display acl all
// Vendor:    h3c
// Rule ID:   13
// Approved:  2026-03-27 by 
// Regenerate: nethelper rule regen 13
package h3c

import (
	"github.com/xavierli/nethelper/internal/model"
	"github.com/xavierli/nethelper/internal/parser/engine"
)

func ParseH3cAclAll(raw string) (model.ParseResult, error) {
	dsl := `# Split input by ACL headers — each ACL block becomes a group
# Parent fields (acl_type, acl_number, acl_name, rule_count) are broadcast to every child row
REPEAT_FOR ^(?P<acl_type>Basic|Advanced|Layer 2) IPv4 ACL (?P<acl_number>\d+) named (?P<acl_name>[^,]+), (?P<rule_count>\d+) rules,
# Within each ACL block, only keep rule lines
FILTER ^rule\s+\d+
# Extract rule components via regex (protocol list is explicit to avoid matching "source"/"destination")
REGEX ^rule\s+(?P<rule_id>\d+)\s+(?P<action>permit|deny)(?:\s+vpn-instance\s+(?P<vpn>\S+))?(?:\s+(?P<protocol>ip|tcp|udp|icmp|igmp|gre|ospf|[0-9]+))?(?:\s+source\s+(?P<source_ip>\S+)\s+(?P<source_wildcard>\S+))?(?:\s+destination\s+(?P<dest_ip>\S+)\s+(?P<dest_wildcard>\S+))?(?:\s+\((?P<hit_count>\d+) times matched\))?
`
	result, err := engine.ExecPipeline(dsl, raw)
	if err != nil {
		return model.ParseResult{RawText: raw}, err
	}
	return model.ParseResult{
		Type:    model.CommandType("generated:h3c:acl_all"),
		RawText: raw,
		Rows:    result.Rows,
	}, nil
}
