// Code generated by nethelper rule-studio. DO NOT EDIT.
// This file is maintained by the Code Generator. Add rules via `nethelper rule studio`.
package h3c

import (
	"strings"

	"github.com/xavierli/nethelper/internal/model"
)

// classifyGenerated is a fallback called by ClassifyCommand when the main switch
// returns CmdUnknown. Rule Studio inserts cases here automatically.
func classifyGenerated(cmd string) model.CommandType {
	switch {
	case strings.HasPrefix(cmd, "display ip inter brief"):
		return model.CommandType("generated:h3c:ip_inter_brief") // ParseH3cIpInterBrief
	case strings.HasPrefix(cmd, "display link-aggregation verbose bridge-aggregation 1"):
		return model.CommandType("generated:h3c:link_aggregation_verbose_bridge_aggregation_1") // ParseH3cLinkAggregationVerboseBridgeAggregation1
	case strings.HasPrefix(cmd, "display acl all"):
		return model.CommandType("generated:h3c:acl_all") // ParseH3cAclAll
	case strings.HasPrefix(cmd, "display route-policy"):
		return model.CommandType("generated:h3c:route_policy") // ParseH3cRoutePolicy
	// GENERATED CASES — do not edit this comment
	}
	return model.CmdUnknown
}

// parseGenerated is a fallback called by ParseOutput for Rule Studio-generated commands.
// Rule Studio inserts dispatch cases here automatically (one per approved rule).
func parseGenerated(cmdType model.CommandType, raw string) (model.ParseResult, error) {
	switch cmdType {
	case model.CommandType("generated:h3c:ip_inter_brief"):
		return ParseH3cIpInterBrief(raw)
	case model.CommandType("generated:h3c:link_aggregation_verbose_bridge_aggregation_1"):
		return ParseH3cLinkAggregationVerboseBridgeAggregation1(raw)
	case model.CommandType("generated:h3c:acl_all"):
		return ParseH3cAclAll(raw)
	case model.CommandType("generated:h3c:route_policy"):
		return ParseH3cRoutePolicy(raw)
	// GENERATED PARSE CASES — do not edit this comment
	}
	return model.ParseResult{Type: cmdType, RawText: raw}, nil
}

// generatedCmdTypes returns CommandType values for all approved Rule Studio rules.
func generatedCmdTypes() []model.CommandType {
	return []model.CommandType{
		model.CommandType("generated:h3c:ip_inter_brief"),
		model.CommandType("generated:h3c:link_aggregation_verbose_bridge_aggregation_1"),
		model.CommandType("generated:h3c:acl_all"),
		model.CommandType("generated:h3c:route_policy"),
		// GENERATED CMDTYPES — do not edit this comment
	}
}

// generatedFieldSchema returns FieldDef slices for Rule Studio generated parsers.
func generatedFieldSchema(cmdType model.CommandType) []model.FieldDef {
	switch cmdType {
	case model.CommandType("generated:h3c:ip_inter_brief"):
		return nil
	case model.CommandType("generated:h3c:link_aggregation_verbose_bridge_aggregation_1"):
		return nil
	case model.CommandType("generated:h3c:acl_all"):
		return nil
	case model.CommandType("generated:h3c:route_policy"):
		return nil
	// GENERATED FIELD CASES — do not edit this comment
	}
	return nil
}
