// Code generated by nethelper rule-studio. DO NOT EDIT.
package h3c_test

import (
	"testing"

	"github.com/xavierli/nethelper/internal/parser/h3c"
)


func TestParseH3cIpInterBrief_Case0(t *testing.T) {
	input := "*down: administratively down\n(s): spoofing\nInterface                     Physical Protocol IP Address      Description \nFGE2/0/1                      up       up       10.48.58.244    SH-YQ-050...\nFGE2/0/2                      up       up       10.48.58.246    SH-YQ-050...\nFGE2/0/3                      up       up       10.48.58.248    SH-YQ-050..."
	_, err := h3c.ParseH3cIpInterBrief(input)
	if err != nil {
		t.Errorf("case 0: unexpected error: %v", err)
	}
	// Expected result saved: {
  "rows": [
    {
      "admin_down": "no",
      "description": "SH-YQ-050...",
      "interface": "FGE2/0/2",
      "ip_address": "10.48.58.246",
      "physical": "up",
      "physical_clean": "up",
      "protocol": "up",
      "protocol_clean": "up",
      "spoofing": "no"
    },
    {
      "admin_down": "no",
      "description": "SH-YQ-050...",
      "interface": "FGE2/0/3",
      "ip_address": "10.48.58.248",
      "physical": "up",
      "physical_clean": "up",
      "protocol": "up",
      "protocol_clean": "up",
      "spoofing": "no"
    }
  ],
  "columns": [
    "interface",
    "physical",
    "protocol",
    "ip_address",
    "description"
  ],
  "mode": "table"
}
	// TODO: parse expected JSON and assert returned fields (see deferred)
}

