// Code generated by nethelper rule-studio. DO NOT EDIT.
package h3c_test

import (
	"testing"

	"github.com/xavierli/nethelper/internal/parser/h3c"
)


func TestParseH3cLinkAggregationVerboseBridgeAggregation1_Case0(t *testing.T) {
	input := "Loadsharing Type: Shar -- Loadsharing, NonS -- Non-Loadsharing \nPort Status: S -- Selected, U -- Unselected, I -- Individual \nFlags:  A -- LACP_Activity, B -- LACP_Timeout, C -- Aggregation, \nD -- Synchronization, E -- Collecting, F -- Distributing,  \nG -- Defaulted, H -- Expired\n\nAggregate Interface: Bridge-Aggregation1\nAggregation Mode: Dynamic\nLoadsharing Type: Shar\nSystem ID: 0x8000, 3c8c-4004-d3d0\nLocal: \nPort             Status  Priority Oper-Key  Flag\n--------------------------------------------------------------------------------\nXGE2/0/35:1      S       32768    1         {ACDEF}\nXGE3/0/35:1      S       32768    1         {ACDEF}\nRemote: \nActor            Partner Priority Oper-Key  SystemID               Flag   \n--------------------------------------------------------------------------------\nXGE2/0/35:1      5       32768    4         0x8000, 741f-4a2e-0aa0 {ACDEF}\nXGE3/0/35:1      6       32768    4         0x8000, 741f-4a2e-0aa0 {ACDEF}\n<SH-YQ-0502-E16-H12516AF-LC-01>\n<SH-YQ-0502-E16-H12516AF-LC-01>\n<SH-YQ-0502-E16-H12516AF-LC-01>\n<SH-YQ-0502-E16-H12516AF-LC-01>"
	_, err := h3c.ParseH3cLinkAggregationVerboseBridgeAggregation1(input)
	if err != nil {
		t.Errorf("case 0: unexpected error: %v", err)
	}
	// Expected result saved: {
  "rows": [
    {
      "local_flag": "ACDEF",
      "local_oper_key": "1",
      "local_port": "XGE2/0/35:1",
      "local_priority": "32768",
      "local_status": "S",
      "remote_flag": "ACDEF",
      "remote_oper_key": "4",
      "remote_partner": "5",
      "remote_port": "XGE2/0/35:1",
      "remote_priority": "32768",
      "remote_sys1": "0x8000,",
      "remote_sys2": "741f-4a2e-0aa0",
      "remote_systemid": "0x8000, 741f-4a2e-0aa0"
    },
    {
      "local_flag": "ACDEF",
      "local_oper_key": "1",
      "local_port": "XGE3/0/35:1",
      "local_priority": "32768",
      "local_status": "S",
      "remote_flag": "ACDEF",
      "remote_oper_key": "4",
      "remote_partner": "6",
      "remote_port": "XGE3/0/35:1",
      "remote_priority": "32768",
      "remote_sys1": "0x8000,",
      "remote_sys2": "741f-4a2e-0aa0",
      "remote_systemid": "0x8000, 741f-4a2e-0aa0"
    }
  ],
  "columns": [
    "local_port",
    "local_status",
    "local_priority",
    "local_oper_key",
    "local_flag",
    "remote_port",
    "remote_partner",
    "remote_priority",
    "remote_oper_key",
    "remote_sys1",
    "remote_sys2",
    "remote_flag",
    "remote_systemid"
  ],
  "mode": "table"
}
	// TODO: parse expected JSON and assert returned fields (see deferred)
}

