// Code generated by nethelper rule-studio. DO NOT EDIT.
// Command:   display route-policy
// Vendor:    h3c
// Rule ID:   17
// Approved:  2026-03-27 by 
// Regenerate: nethelper rule regen 17
package h3c

import (
	"github.com/xavierli/nethelper/internal/model"
	"github.com/xavierli/nethelper/internal/parser/engine"
)

func ParseH3cRoutePolicy(raw string) (model.ParseResult, error) {
	dsl := `# H3C display route-policy parser
# Parses route-policy definitions with nested permit/deny rules

# First level: split by route-policy headers
REPEAT_FOR ^Route-policy:\s+(?P<policy_name>\S+)$

# Second level: split each policy into permit/deny blocks
REPEAT_FOR ^(?P<action_type>Permit|Deny)\s*:\s*(?P<seq_num>\d+)$

# Match if-match conditions (can be multiple, accumulate)
REGEX ^if-match\s+(?P<match_rest>.+)$
SET $match_condition $match_rest

# Match apply actions (can be multiple, accumulate)
REGEX ^apply\s+(?P<apply_rest>.+)$
SET $apply_action $apply_rest

# Skip blank lines and prompt lines
SKIP_BLANK
REJECT ^<.*>$
`
	result, err := engine.ExecPipeline(dsl, raw)
	if err != nil {
		return model.ParseResult{RawText: raw}, err
	}
	return model.ParseResult{
		Type:    model.CommandType("generated:h3c:route_policy"),
		RawText: raw,
		Rows:    result.Rows,
	}, nil
}
